// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using TernakSepatu.Data;
using TernakSepatu.Models;

#nullable disable

namespace TernakSepatu.Migrations
{
    [DbContext(typeof(TernakSepatuDBContext))]
    [Migration("20240331072748_LandingPageTable")]
    partial class LandingPageTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity<LandingPage>(entity =>
            {
                entity.ToTable("LandingPage");

                entity.Property(e => e.Id).HasColumnName("Id").HasColumnType("int")
                    .ValueGeneratedOnAdd();

                entity.Property(e => e.ImageURL)
                    .IsRequired()
                    .HasColumnName("ImageURL")
                    .HasColumnType("nvarchar(max)");

                entity.Property(e => e.Text)
                    .IsRequired()
                    .HasColumnName("Text")
                    .HasColumnType("nvarchar(max)");

                entity.Property(e => e.Status)
                    .HasColumnName("Status")
                    .HasColumnType("nvarchar(max)")
                    .HasDefaultValue("aktif");

                entity.Property(e => e.CreateAt)
                    .HasColumnName("CreateAt")
                    .HasColumnType("datetime");
            });
        }
    }
}
